# Generated by Django 3.2.4 on 2021-06-29 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=36)),
                ('modified_by', models.CharField(max_length=36)),
                ('code', models.CharField(max_length=12)),
                ('start_date', models.DateTimeField()),
                ('expire_date', models.DateTimeField()),
                ('customer_id', models.CharField(max_length=36)),
                ('limited_usage_count', models.IntegerField(default=1)),
                ('usage_count', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'discount_codes',
            },
        ),
    ]
